#! /usr/bin/env python2.7

from sys import argv, exit, stdin, stdout
from Bio import SeqIO
from optparse import OptionParser

opt_reader = OptionParser()
opt_reader.add_option('-l', '--minlength', type='int', default=0, help='Require a minimum length')
(opts, args) = opt_reader.parse_args()

if len(args) == 0:
   opt_reader.print_help()
   exit(0)

try:
   ih = stdin
   if (args[0] != '--'):
      ih = open(args[0])
except IOError as e:
   print "Could not open file."
   exit(1)

seqs = {}
fileformat = 'fasta'			# Assume fasta for now

for rec in SeqIO.parse(ih, fileformat):
   if len(rec.seq) > opts.minlength:
      SeqIO.write(rec, stdout, fileformat)


