#! /usr/bin/perl -w
#


use strict;

my $usage = "Usage: seqgrep <pattern> <seqdbfilename>

The pattern is looked for in the locus line in the FASTA formatted
sequence file. Beware! The pattern is handed off to PERL's RegExp
engine as-is.

";

if (scalar(@ARGV) != 2) {
  die $usage;
}

my $pattern = shift @ARGV;
my $dbname = shift @ARGV;

my $do_copy = 0;

# Iterate through the massive DB file and see if a sequence has been caught in the search.
# Output the domain sequences!
open (F, "<$dbname")
  or die "Could not open '$dbname' for reading!";

while (<F>) {
  if (m/^>.*$pattern.*$/) {
    $do_copy = 1;
    print $_;
  } elsif (m/^>(\S+)/) {
    $do_copy = 0;
  } elsif ($do_copy) {
    print $_;
  }
}
