#! /usr/bin/perl -w
#


use strict;

my $usage = "Usage: seqmap <cmd> <fastafile>

The command given in the first argument is executed for 
each sequence in the FASTA file. The current sequence
is found in the file 'tmp.fa' and its accession is given 
in the environment variable \$SEQACC.

Example usage:
  > seqmap \"echo \\\$SEQACC; cat\" seqs.fa

Note how the dollar sign is protected.
";

if (scalar(@ARGV) != 2) {
  die $usage;
}

my $cmd = shift @ARGV;
my $dbname = shift @ARGV;

# Iterate through the massive DB file and execute the command
open (F, "<$dbname")
  or die "Could not open '$dbname' for reading!";

my $cur_name = '';
my $cur_seq = '';
while (<F>) {
  if (m/^>(\S+)/) {
    if (length($cur_name) > 0) {
      run_cmd($cur_name, $cur_seq);
    }
    $cur_name = $1;
    $cur_seq = "";
  } elsif (m/\S/) {
    $cur_seq .= $_;
  }
}
if (length($cur_seq) > 0) {
  run_cmd($cur_name, $cur_seq);
}
close(F);


sub run_cmd {
  my ($cur_name, $cur_seq) = @_;

  open(G, ">tmp.fa") || die "Aj aj aj ($?)";
  print G ">$cur_name\n";
  print G "$cur_seq\n";
  close(G);
  my @parts = split(/\|/, $cur_name);
  $cur_name = pop @parts;

#  $cur_name =~ s/^\S+\|(\S+)/$1/;
#  $cur_name =~ s/\|/\_/g;
#        print STDERR "name='$cur_name'\n";
  #      print STDERR "cmd='$cmd'\n";
  #      my $fullcmd = "export SEQACC=$cur_name; $cmd tmp.fa;\n";
  my $fullcmd = "export SEQACC=$cur_name; $cmd ; rm tmp.fa\n";
  #      print STDERR $fullcmd;
  system($fullcmd);

}
