#! /usr/bin/perl -w
#


use strict;

my $usage = "Usage: seqstrip <seqdbfilename>

Remove indels and other non-characters from sequence.

";

if (@ARGV > 0 && ($ARGV[0] eq '-u' || $ARGV[0] eq '-h')) {
  die $usage;
}

my $cur_name = '';
my $cur_seq = '';
while (<>) {
  chomp;
  if (m/^(>\S+)/) {
    if (length($cur_name) > 0) {
      $cur_seq =~ s/[-_\. ]//g;
      print $cur_name, "\n", $cur_seq, "\n";
    }
    $cur_name = $1;
    $cur_seq = '';
  } elsif (m/\S/) {
    $cur_seq .= $_;
  }
}
if (length($cur_seq) > 0) {
  $cur_seq =~ s/[-_\. ]//g;
  print $cur_name, "\n", $cur_seq, "\n";
}

