#! /usr/bin/env python2.7
from Bio import SeqIO
import sys

for genome in SeqIO.parse(sys.stdin,'genbank'):
    for gene in genome.features:
        if gene.type != "CDS":
            continue
        if 'gene' not in gene.qualifiers:
            continue
        # if 'cox3' not in gene.qualifiers['gene'][0].lower():
        #     continue
        acc = str(gene.qualifiers['gene'][0])
        product = str(gene.qualifiers['product'][0])
        protein = str(gene.qualifiers['protein_id'][0])
        gene_seq = gene.extract(genome.seq)
        if 'db_xref' in gene.qualifiers:
            gi = str(gene.qualifiers['db_xref']).split(":")[1].split("'")[0]
        else:
            gi = "NoGenID"
        print ">lcl|%s|gi|%s Protein: %s %s\n%s" % (acc, gi, protein, product, gene_seq)
