#! /usr/bin/perl -w
#


use strict;

my $usage = "Usage: seqextract <idfile> <seqdbfilename>

Sequence ids from <idfile> are looked for in the locus line in the FASTA formatted
sequence file.

";

if (scalar(@ARGV) != 2) {
  die $usage;
}

my $patternfilename = shift @ARGV;
my $dbname = shift @ARGV;

open(IDFILE, "<$patternfilename")
    or die "Could not open '$patternfilename' for reading!";

my %ids = {};
while (<IDFILE>) {
    chomp;
    $ids{$_} = 1;
}

if (scalar(keys(%ids)) == 0) {
    print STDERR "No accessions/ids found in '$patternfilename'!";
    exit 1;
}

my $do_copy = 0;

# Iterate through the massive DB file and see if a sequence has been caught in the search.
# Output the domain sequences!
open (F, "<$dbname")
  or die "Could not open '$dbname' for reading!";

while (<F>) {
  if (m/^>\s*(\S+)\s*/) {
      if (defined $ids{$1}) {
	  $do_copy = 1;
	  print $_;
      } else {
	  $do_copy = 0;
      }
  } elsif ($do_copy) {
    print $_;
  }
}
